import React, { useState, useEffect } from 'react';
import { Note } from '../types';
import Markdown from 'react-markdown';
import { Mic, Clock, ListChecks, ChevronRight, Loader2 } from 'lucide-react';

export function NotesView() {
  const [notes, setNotes] = useState<Note[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedNote, setSelectedNote] = useState<Note | null>(null);

  useEffect(() => {
    fetch('/api/notes')
      .then(res => res.json())
      .then(data => {
        setNotes(data);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, []);

  return (
    <div className="h-[calc(100vh-6rem)] flex gap-6">
      {/* List */}
      <div className="w-1/3 flex flex-col border border-slate-800 bg-[#0f1525] rounded-2xl overflow-hidden shadow-xl shrink-0">
        <div className="p-5 border-b border-slate-800 bg-slate-900/50">
          <h2 className="text-lg font-medium flex items-center gap-2">
            <Mic className="w-5 h-5 text-emerald-400" />
            Voice Notes Hub
          </h2>
        </div>
        <div className="overflow-y-auto flex-1 p-3 space-y-2 custom-scrollbar">
          {loading ? (
            <div className="p-8 flex justify-center"><Loader2 className="w-5 h-5 animate-spin text-slate-500" /></div>
          ) : notes.map(note => (
            <button
              key={note.filename}
              onClick={() => setSelectedNote(note)}
              className={`w-full text-left p-4 rounded-xl transition-all ${
                selectedNote?.filename === note.filename 
                  ? 'bg-emerald-500/10 border-emerald-500/20 border shadow-sm' 
                  : 'bg-slate-800/30 border-transparent border hover:bg-slate-800/60'
              }`}
            >
              <div className="flex justify-between items-start mb-2">
                <h3 className="font-mono text-sm text-slate-200 truncate pr-4">{note.filename}</h3>
                <ChevronRight className={`w-4 h-4 shrink-0 ${selectedNote?.filename === note.filename ? 'text-emerald-400' : 'text-slate-600'}`} />
              </div>
              <div className="flex items-center gap-1.5 text-xs text-slate-500 font-mono">
                <Clock className="w-3.5 h-3.5" />
                {new Date(note.mtime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Detail Panel */}
      <div className="flex-1 border border-slate-800 bg-[#0f1525] rounded-2xl overflow-hidden shadow-xl flex flex-col relative">
        {selectedNote ? (
          <>
            <div className="p-6 border-b border-slate-800 bg-slate-900/50 flex justify-between items-start">
              <div>
                <div className="text-xs font-mono text-emerald-400 mb-2">TRANSCRIPT</div>
                <h2 className="text-xl font-medium text-slate-100">{selectedNote.filename}</h2>
              </div>
              <div className="text-xs font-mono text-slate-500 bg-slate-800/50 px-3 py-1.5 rounded-full border border-slate-700/50">
                {new Date(selectedNote.mtime).toLocaleString()}
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto p-8 grid grid-cols-1 xl:grid-cols-3 gap-8">
              <div className="xl:col-span-2 markdown-body">
                <Markdown>{selectedNote.content}</Markdown>
              </div>
              
              {/* AI Action Items Side Panel */}
              <div className="xl:col-span-1 border-l border-slate-800 pl-8">
                <div className="flex items-center gap-2 mb-6">
                  <ListChecks className="w-5 h-5 text-blue-400" />
                  <h3 className="text-sm font-medium text-slate-200 uppercase tracking-wider">AI Action Items</h3>
                </div>
                <div className="space-y-4">
                  {[1, 2].map(i => (
                    <div key={i} className="p-4 rounded-xl bg-slate-800/30 border border-slate-700/50">
                      <p className="text-sm text-slate-300 mb-3">Extracted task from context paragraph {i}. Review the mentioned documentation.</p>
                      <button className="text-xs font-mono text-blue-400 hover:text-blue-300 transition-colors">ADD TO PROTOCOL →</button>
                    </div>
                  ))}
                  <div className="text-xs text-slate-500 italic mt-4">
                    Auto-generated by extraction agent.
                  </div>
                </div>
              </div>
            </div>
          </>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-slate-500">
            <Mic className="w-12 h-12 mb-4 opacity-20" />
            <p>Select a voice note to view transcript & actions</p>
          </div>
        )}
      </div>
    </div>
  );
}
